<?php
	$_code = $this->getMethodCode();
	$_crypto = Mage::helper('crypto');
	$quotes = $_crypto->getCoinQuotes();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
<?php
	if(!empty($quotes)){
?>

	    <li>
			<?php echo $this->__('Select from available crypto-currencies quotes below') ?>
	    </li>


<?php
	foreach($quotes as $currency){
?>
	    <li>
		<label for="<?php echo $_code ?>_currency_<?php echo $currency['code'];?>"><?php echo $currency['quote'];?> <?php echo $currency['code'];?></label>
		<span class="radio-box">
		     <input type="radio" value="<?php echo $currency['code'];?>" id="<?php echo $_code ?>_currency_<?php echo $currency['code'];?>" name="payment[crypto_currency]">
		</span>
	    </li>
<?php   }}else{?>
    <li>
	Blast! There are no crypto-currencies available at this time.
    </li>
<?php   }?>
    <li>
	<p>Rates are provided by <a href="https://coinbench.io" target="_blank">Coinbench</a> and are subject to change until you submit your order.</p>	
    </li>
</ul>

<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
