<style>
    .crytohint{
        background: none repeat scroll 0 0 #EAF0EE;
        border: 1px solid #CCCCCC;
        margin-bottom: 10px;
        padding: 11px 0 0 10px;
    }
</style>

<div class="crytohint">
    <h4><strong style="color:#EA7601;">Coinbench Crypto Payment v<?php echo $this->getCryptoVersion(); ?></strong></h4>
    <p><strong><a href="http://coinbench.io" target="_blank">Get a free Coinbench account</a> and start accepting Bitcoin today</strong></p>
    <p>Updates go out on twitter <a href="http://twitter.com/coinbench" target="_blank">@Coinbench</a>.</p>
</div>
