<style>
    .crytohint{
        background: none repeat scroll 0 0 #EAF0EE;
        border: 1px solid #CCCCCC;
        margin-bottom: 10px;
        padding: 11px 0 0 10px;
    }
</style>

<div class="crytohint">
    <h4><strong style="color:#EA7601;">Coinbench Crypto Payment v<?php echo $this->getCryptoVersion(); ?></strong></h4>
    <p><strong><a href="http://coinbench.io" target="_blank">Get a free Coinbench account</a> and start accepting Bitcoin today</strong></p>
    <p>Free Magento extension maintained by <a href="http://www.madcapsule.com" target="_blank">Mad Capsule Media</a></p>
    <p>Follow on <a href="http://twitter.com/coinbench" target="_blank">@Coinbench</a> and <a href="http://twitter.com/madcapsulemedia" target="_blank">@MadCapsuleMedia</a> on twitter</p>
</div>
