<?php 
	$order = $this->transactionDetail();
	$currency = $order['crypto_currency'];
	$amount = $order['crypto_amount'];
	$address = $order['crypto_address'];

?>

<h2 class="sub-title"><?php echo $this->__('Instructions to Complete Your Transaction') ?></h2>

<p>
Please send <?php echo $amount.$currency;?> to the address below, or scan the QR code within 1 hour to complete your purchase.
</p>

<p><strong>Address: <?php echo $address;?></strong></p>

<div id="qr" style="width:150px;height:150x;"></div>

<script>
var draw_qrcode = function(text, typeNumber, errorCorrectLevel) {
	document.write(create_qrcode(text, typeNumber, errorCorrectLevel) );
};

var create_qrcode = function(text, typeNumber, errorCorrectLevel, table) {

	var qr = qrcode(typeNumber || 4, errorCorrectLevel || 'M');
	qr.addData(text);
	qr.make();

//	return qr.createTableTag();
	return qr.createImgTag();
};

	var text = '<?php echo $address;?>'.
		replace(/^[\s\u3000]+|[\s\u3000]+$/g, '');
	document.getElementById('qr').innerHTML = create_qrcode(text);
</script>
